CREATE TABLE ITEM_GROUPS
(
    ID   INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR NOT NULL
);
CREATE INDEX ITEM_GROUPS_IX_NAME ON ITEM_GROUPS (NAME);

CREATE TABLE ITEMS
(
    ID           INTEGER NOT NULL PRIMARY KEY,
    NAME         VARCHAR NOT NULL,
    EXAMINE_TEXT TEXT    NOT NULL,
    GROUP_ID     INT     NOT NULL,
    VERSION      VARCHAR NULL,
    URL          TEXT    NOT NULL,
    IS_MEMBERS   BOOL    NOT NULL,
    IS_TRADEABLE BOOL    NOT NULL,
    SEARCH_NAME  VARCHAR NOT NULL,
    FOREIGN KEY (GROUP_ID) REFERENCES ITEM_GROUPS (ID)
);
CREATE INDEX I_GROUP_ID ON ITEMS (GROUP_ID);
CREATE INDEX I_NAME ON ITEMS (SEARCH_NAME);

-- 1:1 productions:outputs
CREATE TABLE PRODUCTION_RECIPES
(
    ID                   INTEGER NOT NULL PRIMARY KEY,
    TICKS                TEXT    NULL,
    FACILITIES           TEXT    NULL,
    TOOLS                TEXT    NULL,
    IS_MEMBERS           BOOL    NOT NULL,
    OUTPUT_ITEM_NAME     VARCHAR NULL,
    OUTPUT_ITEM_VERSION  VARCHAR NULL,
    OUTPUT_ITEM_ID       INT     NULL,
    OUTPUT_QUANTITY      TEXT    NOT NULL,
    OUTPUT_QUANTITY_NOTE TEXT    NULL,
    OUTPUT_SUBTEXT       TEXT    NULL
);
CREATE INDEX PR_ITEM_ID ON PRODUCTION_RECIPES (OUTPUT_ITEM_ID);
-- CREATE INDEX PR_ITEM_NAME ON PRODUCTION_RECIPES (OUTPUT_ITEM_NAME);
-- CREATE INDEX PR_ITEM_VERSION ON PRODUCTION_RECIPES (OUTPUT_ITEM_VERSION);

-- 1:1 materials:items
-- N:1 materials:productions
CREATE TABLE PRODUCTION_MATERIALS
(
    ID           INTEGER NOT NULL PRIMARY KEY,
    RECIPE_ID    INT     NOT NULL,
    ITEM_NAME    VARCHAR NULL,
    ITEM_VERSION VARCHAR NULL,
    ITEM_ID      INT     NULL,
    QUANTITY     TEXT    NULL
);
CREATE INDEX PM_ITEM_ID ON PRODUCTION_MATERIALS (ITEM_ID);
-- CREATE INDEX PM_ITEM_NAME ON PRODUCTION_MATERIALS (ITEM_NAME);
-- CREATE INDEX PM_ITEM_VERSION ON PRODUCTION_MATERIALS (ITEM_VERSION);

-- N:1 skills:productions
CREATE TABLE PRODUCTION_SKILLS
(
    ID           INTEGER NOT NULL PRIMARY KEY,
    RECIPE_ID    INT     NOT NULL,
    NAME         TEXT    NOT NULL,
    LEVEL        TEXT    NOT NULL,
    EXPERIENCE   TEXT    NOT NULL,
    IS_BOOSTABLE BOOL    NOT NULL
);

CREATE TABLE SHOPS
(
    ID              INTEGER NOT NULL PRIMARY KEY,
    NAME            TEXT    NOT NULL,
    SELL_MULTIPLIER TEXT    NULL,
    LOCATION        TEXT    NOT NULL,
    IS_MEMBERS      BOOL    NOT NULL
);

-- 1:1 shop_items:items
-- 1:1 shop_items:shops
CREATE TABLE SHOP_ITEMS
(
    ID           INTEGER NOT NULL PRIMARY KEY,
    ITEM_NAME    VARCHAR NULL,
    ITEM_VERSION VARCHAR NULL,
    ITEM_ID      INT     NULL,
    SHOP_ID      INT     NOT NULL,
    CURRENCY     TEXT    NOT NULL,
    STOCK        TEXT    NOT NULL,
    BUY_PRICE    TEXT    NULL,
    SELL_PRICE   TEXT    NULL
);
CREATE INDEX SI_ITEM_ID ON SHOP_ITEMS (ITEM_ID);
--CREATE INDEX SI_ITEM_NAME ON SHOP_ITEMS (ITEM_NAME);
--CREATE INDEX SI_ITEM_VERSION ON SHOP_ITEMS (ITEM_VERSION);

-- N:1 spawn_items:item_groups
CREATE TABLE SPAWN_ITEMS
(
    ID         INTEGER NOT NULL PRIMARY KEY,
    GROUP_ID   INT     NOT NULL,
    NAME       VARCHAR NOT NULL,
    COORDS     TEXT    NOT NULL,
    LOCATION   TEXT    NOT NULL,
    IS_MEMBERS BOOL    NOT NULL
);
CREATE INDEX PI_ITEM_NAME ON SPAWN_ITEMS (NAME);

-- N:1 drop_sources:items
CREATE TABLE DROP_SOURCES
(
    ID            INTEGER NOT NULL PRIMARY KEY,
    ITEM_NAME     VARCHAR NULL,
    SOURCE        TEXT    NOT NULL,
    QUANTITY_LOW  INT     NOT NULL,
    QUANTITY_HIGH INT     NOT NULL,
    RARITY        TEXT    NOT NULL,
    DROP_LEVEL    TEXT    NOT NULL,
    DROP_TYPE     TEXT    NOT NULL
);
CREATE INDEX DS_ITEM_NAME ON DROP_SOURCES (ITEM_NAME);
